### PR TITLE
replace global mutex protected rand

### PR DESCRIPTION
**Pull request by coocood**

### CODE REVIEW

**Comment by ngaut** [comment]
You could use https://golang.org/pkg/math/rand/#NewSource instead of the hack.

**Comment by coocood** [comment]
This is faster, 2ns instead of 6ns.

**Comment by coocood** [comment]
Another benefit is that it supports concurrent Put on the same SkipList.

**Comment by ngaut** [comment]
We are not using concurrent putting currently, Am i right?

**Comment by coocood** [comment]
Yes, so the main reason is it is faster.

**Pull request merged**
